### ISSUE TITLE
Encoding issue?

### ISSUE THREAD

**Issue by ardumont** [dulwich/dulwich#608]
Hello,

I have a repository whose refs/commit messages are in cyrillic:

```
>>> import os
>>> list(os.walk(b'refs/heads'))
[(b'refs/heads', [], [b'\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01', b'master'])]
>>> s = b'\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01'
>>> s.decode('latin1')
'Íîâàÿâåòêà1'  # seems like rubbish
>>> s.decode('cp1251')
'Новаяветка1'  # looks like russian  -> google translates agrees: `newlight1`
```
[google-translates 'Новаяветка1' as `newlight1`](https://translate.google.com/#auto/fr/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%D0%B2%D0%B5%D1%82%D0%BA%D0%B01).

... and somehow, that makes dulwich break:
```
$ python3
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r.refs
DiskRefsContainer('.')
>>> r.refs.allkeys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 470, in allkeys
    sys.getfilesystemencoding())
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 11-20: surrogates not allowed
```

Is is the expected behavior?

[I think not according to the doc.](https://github.com/jelmer/dulwich/blob/a0e591771c501a93253ac1ebc19eebc6f45e0d4d/docs/tutorial/encoding.txt#L14-L16)

Do you know how could i overcome this?

Thanks for your help.

Cheers,

**Comment by jelmer** [comment]
Yes, this is a bug. Does list(os.walk("refs/heads")) (no b) work, and what does it return?

**Comment by ardumont** [comment]
Hello,

> Yes, this is a bug. 

Ok.

> Does list(os.walk("refs/heads")) (no b) work, and what does it return?

I'm not sure what qualifies as 'work' ;)

As far as i understood the [os module](https://docs.python.org/3/library/os.html#module-os), the output  format is supposed to match the input format, so `bytes in, bytes out` or `str in, str out`.

In any case, what you asked returns the following:
```
Python 3.6.4 (default, Jan  5 2018, 02:13:53)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
$ python3
>>> import os
>>> list(os.walk('refs/heads'))
[('refs/heads', [], ['\udccd\udcee\udce2\udce0\udcff\udce2\udce5\udcf2\udcea\udce01', 'master'])]
```

Cheers,

**Comment by jelmer** [comment]
Fixed in master.

**Comment by ardumont** [comment]
> Fixed in master.

I confirm \m/

```
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> list(os.walk(b'refs/heads'))
[(b'refs/heads', [], [b'\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01', b'master'])]
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r.refs
DiskRefsContainer('.')
>>> r.refs.allkeys()
{b'refs/heads/master', b'refs/heads/\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01', b'HEAD'}
>>>
```

Thanks!

**Comment by ardumont** [comment]
I spoke too soon, I still have issues down the line (https://forge.softwareheritage.org/T911 for history/details ;)

```
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r.refs
{b'refs/heads/master', b'refs/heads/\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01', b'HEAD'}
>>> r.get_refs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/dulwich/repo.py", line 348, in get_refs
    return self.refs.as_dict()
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 188, in as_dict
    ret[key] = self[(base + b'/' + key).strip(b'/')]
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 271, in __getitem__
    _, sha = self.follow(name)
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 243, in follow
    contents = self.read_ref(refname)
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 217, in read_ref
    contents = self.read_loose_ref(refname)
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 604, in read_loose_ref
    filename = self.refpath(name)
  File "/usr/lib/python3/dist-packages/dulwich/refs.py", line 530, in refpath
    name = name.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 11: invalid continuation byte
```

Patching [dulwich.refs.refpath function](https://github.com/dulwich/dulwich/blob/master/dulwich/refs.py#L524-L538) to try and detect the encoding when failing to use the system's encoding seems to be enough:

```
def refpath(self, name):
    """Return the disk path of a ref.

    """
    if (getattr(self.path, "encode", None) and
            getattr(name, "decode", None)):
        try:
            name = name.decode(sys.getfilesystemencoding())
        except UnicodeDecodeError:
            from chardet import detect
            name = name.decode(detect(name)['encoding'])
    if os.path.sep != "/":
        name = name.replace("/", os.path.sep)
    # TODO: as the 'HEAD' reference is working tree specific, it
    # should actually not be a part of RefsContainer
    if name == 'HEAD':
        return os.path.join(self.worktree_path, name)
    else:
        return os.path.join(self.path, name)
```

Then again:

```
>>> from dulwich.repo import Repo
>>> r = Repo('.')
>>> r.refs
DiskRefsContainer('.')
>>> r.get_refs()
{b'refs/heads/master': b'01893098d620ff74302c5e2c357b979a51074682', b'HEAD': b'01893098d620ff74302c5e2c357b979a51074682'}
```

Would that be a reasonable fix?

Cheers,

**Comment by jelmer** [comment]
The encoding handling should be consistent, otherwise you might end up writing a different encoding back than you originally read (and thus with duplicate refs). Refs should all be bytes, so encoding shouldn't really come into it at all.

I've pushed a fix to master, can you try with that?

**Comment by ardumont** [comment]
> The encoding handling should be consistent, otherwise you might end up writing a different encoding back than you originally read (and thus with duplicate refs). 

Quite!

> Refs should all be bytes, so encoding shouldn't really come into it at all.

I agree.

I did not quite get why the initial code decoded bytes in the first place...
Well for most use cases that should be ok (because users are mostly consistent or at least, they can set things up to be). But from swh use case, which is archive all possible dvcs repositories..., that cannot go well (as we have objectively no control over the repositories's content ;)

So yeah, your solution is way better (deal with bytes ;)
I thought of it. I was not confident enough in measuring impact for such a switch though.

> I've pushed a fix to master, can you try with that?

Yes, will try... Thanks.

And, it works!

```
$ python3
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from swh.loader.git.tasks import LoadDiskGitRepository
KeyboardInterrupt
>>> from dulwich.repo import Repo
>>> r = Repo('test-project2009.git')  # same repo since the issue's opening
>>> r.refs
DiskRefsContainer(b'test-project2009.git')
>>> r.get_refs()
{b'refs/heads/\xcd\xee\xe2\xe0\xff\xe2\xe5\xf2\xea\xe01': b'fcf492990b9e83452491e000ed56aacad56a6681', b'refs/heads/master': b'01893098d620ff74302c5e2c357b979a51074682', b'HEAD': b'01893098d620ff74302c5e2c357b979a51074682'}
```

As usual, thanks for the discussion and the solution ;)

Cheers,
